# Generated by Django 4.0.6 on 2022-07-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortlink', models.CharField(max_length=255)),
                ('longlink', models.TextField()),
            ],
        ),
    ]
